name: Update LicenseDB from the latest scancode-toolkit daily
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_licenseDB:
    name: Daily LicenseDB Update
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Give execute access to the script
        run: chmod u+x ./etc/scripts/check_commit_run_update.sh

      - name: Run script
        run: ./etc/scripts/check_commit_run_update.sh

      - name: Commit and Push to Publish
        run: make html
      
      - name: Clean docs
        run: make publish
